ALTER TABLE user
ADD Quiz11Score INTEGER;

ALTER TABLE user
ADD Quiz12Score INTEGER;

ALTER TABLE user
ADD Quiz13Score INTEGER;

ALTER TABLE user
ADD Quiz14Score INTEGER;

ALTER TABLE user
ADD Quiz15Score INTEGER;

ALTER TABLE user
ADD Quiz16Score INTEGER;

ALTER TABLE user
ADD Quiz17Score INTEGER;

ALTER TABLE user
ADD Quiz18Score INTEGER;

ALTER TABLE user
ADD Quiz19Score INTEGER;

ALTER TABLE user
ADD Quiz20Score INTEGER;

ALTER TABLE user
ADD Quiz21Score INTEGER;

ALTER TABLE user
ADD Quiz22Score INTEGER;